version: '2'

services:
  metafora-db:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    container_name: metafora-db
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=metafora
      - POSTGRESQL_PASSWORD=metafora
      - POSTGRESQL_DATABASE=metafora
      - POSTGRESQL_POSTGRES_PASSWORD=postgres

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    container_name: metafora-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local